services:
  - type: web
    name: unimaintain-backend
    runtime: node
    buildCommand: pnpm install --prod=false && pnpm build
    startCommand: node dist/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
